#!/usr/bin/env python3
"""
generate_build_seed.py
Generates a random 16-byte seed and writes build_seed.h
with XOR obfuscation (minimal protection against `strings`).

The actual password is derived at runtime: KDF_light(seed, board_id).
Each board produces a different password — impossible to recover
from the .uf2 without physical access to the chip.

Usage:
    python3 generate_build_seed.py

    - Run ONCE before each clean build.
    - The password will be printed on Serial at first boot.
    - The build_seed.h file is overwritten on each run.
"""

import os
import secrets


def generate_build_seed(seed_len: int = 16) -> None:
    """
    Generate the seed and write the header with XOR obfuscation.

    Uses os.urandom (via secrets module) for cryptographic-quality
    randomness. The seed, combined with the board_id unique to the
    RP2040, produces a 16-character alphanumeric password via
    irreversible mixing at runtime.
    """

    # --- Generate random seed (16 bytes, cryptographic quality) ---
    seed = list(secrets.token_bytes(seed_len))

    # --- Generate random XOR key (binary obfuscation) ---
    xor_key = list(secrets.token_bytes(seed_len))
    # Ensure no zero bytes in XOR key (would leave seed byte in cleartext)
    for i in range(seed_len):
        while xor_key[i] == 0:
            xor_key[i] = secrets.token_bytes(1)[0]

    # --- Obfuscate: encrypted[i] = seed[i] ^ xor_key[i] ---
    encrypted = [s ^ k for s, k in zip(seed, xor_key)]

    # --- Format C arrays ---
    key_str = ', '.join(f'0x{b:02X}' for b in xor_key)
    enc_str = ', '.join(f'0x{b:02X}' for b in encrypted)

    # --- Write the header ---
    header_content = f"""\
/**
 * @file build_seed.h
 * @brief Compile-time seed for per-board password derivation.
 *        AUTO-GENERATED by generate_build_seed.py — DO NOT EDIT.
 *
 * @details The actual password is derived at runtime:
 *          password = KDF_light(seed, board_id)
 *
 *          Even with access to the .uf2 and seed, the password is
 *          unrecoverable without the physical board_id of the chip.
 *
 *          The derived password (16 alphanumeric chars) is printed
 *          on Serial at first boot and after DEL CONFIRM.
 *
 * @note  Depends on secure_memzero() from keylog_config.h (always
 *        included before this header by crypto_engine.cpp).
 */

#ifndef BUILD_SEED_H
#define BUILD_SEED_H

#include <Arduino.h>
#include <pico/unique_id.h>

/** @brief Seed length in bytes. */
#define BUILD_SEED_LEN {seed_len}

/** @brief Derived password length (alphanumeric characters). */
#define BUILD_PWD_DERIVED_LEN 16

/**
 * @brief XOR key for seed de-obfuscation in the binary.
 * @note  Short names hinder identification via `strings`.
 */
static const uint8_t _bsk[BUILD_SEED_LEN] = {{
    {key_str}
}};

/**
 * @brief Obfuscated seed: _bsd[i] = seed[i] ^ _bsk[i].
 */
static const uint8_t _bsd[BUILD_SEED_LEN] = {{
    {enc_str}
}};

/**
 * @brief Derive build password from compiled seed + board_id.
 *
 * @param out  Output buffer (minimum BUILD_PWD_DERIVED_LEN + 1 bytes).
 *
 * @details Irreversible 64-round mixing with multiply-shift-XOR
 *          operations. The board_id (8 bytes, unique per chip)
 *          makes derivation impossible without physical access.
 *
 * @note  Caller MUST scrub the buffer after use:
 *        secure_memzero(out, BUILD_PWD_DERIVED_LEN + 1);
 */
static inline void deriveBuildPassword(char* out) {{
    /* 1. De-obfuscate the seed */
    uint8_t seed[BUILD_SEED_LEN];
    for (uint8_t i = 0; i < BUILD_SEED_LEN; i++) {{
        seed[i] = _bsd[i] ^ _bsk[i];
    }}

    /* 2. Read the chip's unique board ID */
    pico_unique_board_id_t bid;
    pico_get_unique_board_id(&bid);

    /* 3. Initialize state from seed */
    uint32_t state[4];
    memcpy(state, seed, 16);

    /* 4. Irreversible mixing: seed + board_id (64 rounds) */
    for (uint8_t round = 0; round < 64; round++) {{
        for (uint8_t i = 0; i < 8; i++) {{
            uint8_t si = (i + round) % 4;
            state[si] ^= ((uint32_t)bid.id[i]) << ((round % 4) * 8);
            state[si] *= 0x5BD1E995;
            state[si] ^= state[si] >> 15;
        }}
        /* Avalanche across all state words */
        state[0] += state[3] ^ (round * 0x9E3779B9);
        state[1] ^= state[0] >> 7;
        state[2] += state[1] << 13;
        state[3] ^= state[2] >> 11;
    }}

    /* 5. Encode as alphanumeric (base62) */
    static const char b62[] =
        "0123456789"
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "abcdefghijklmnopqrstuvwxyz";

    uint8_t* raw = (uint8_t*)state;
    for (uint8_t i = 0; i < BUILD_PWD_DERIVED_LEN; i++) {{
        out[i] = b62[raw[i] % 62];
    }}
    out[BUILD_PWD_DERIVED_LEN] = '\\0';

    /* 6. Scrub seed and state from stack (volatile writes, not optimizable) */
    secure_memzero(seed, BUILD_SEED_LEN);
    secure_memzero(state, 16);
}}

#endif // BUILD_SEED_H
"""

    # --- Determine output directory ---
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, 'build_seed.h')

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header_content)

    # --- Print seed info for the user ---
    seed_hex = ' '.join(f'{b:02X}' for b in seed)
    print("=" * 60)
    print("  BUILD SEED GENERATED")
    print("=" * 60)
    print(f"  Seed (hex): {seed_hex}")
    print(f"  Header:     {output_path}")
    print("=" * 60)
    print("  The PASSWORD will be derived from seed + board_id at boot.")
    print("  Connect to Serial to see the password on first boot.")
    print("  Each board will have a DIFFERENT password with the same .uf2.")
    print("=" * 60)


if __name__ == '__main__':
    generate_build_seed()
